Add citation file.
mlpack/ensmallen pull request #317
Opened 2021-08-15 02:04 UTC by zoq

Add citation file to use GitHub's citation feature.

2021-08-15 19:09 UTC, rcurtin commented on CITATION.cff
> +    family-names: "Prabhu "
Seems like no need for an extra space here?

2021-08-25 01:25 UTC, zoq commented
Hm, not sure why the mlpack integration test fails, maybe this was just a fluke.

2021-08-25 01:26 UTC, zoq commented
@mlpack-jenkins test this please

2021-08-31 14:07 UTC, rcurtin approved these changes
Looks good to me---excited to see how this looks once it's merged. :)

2021-09-01 00:30 UTC, conradsnicta requested changes

2021-09-01 00:30 UTC, conradsnicta commented on CITATION.cff
> +    affiliation: "Data61/CSIRO, Griffith University"
@zoq should be "Data61/CSIRO and Griffith University"  
(it's two separate organisations)
```suggestion
    affiliation: "Data61/CSIRO and Griffith University"
```

2021-09-06 00:02 UTC, conradsnicta approved these changes

2021-09-06 00:03 UTC, merged

2021-09-06 00:09 UTC, conradsnicta commented
@zoq @rcurtin so after merging this, turns out GitHub prefers to provide the wrong citation when clicking on "Cite this repository" (left hand side on desktop view).

Instead of citing the JMLR article, this is what's provided by GitHub:
```@misc{Curtin_The_ensmallen_library,author = {Curtin, Ryan R. and Edel, Marcus and Prabhu, Rahul Ganesh and Basak, Suryoday and Lou, Zhihao and Sanderson, Conrad},title = {{The ensmallen library for flexible numerical optimization}},url {https://github.com/mlpack/ensmallen}}```