Bump minimum Armadillo version to 9.800.
mlpack/ensmallen pull request #318
Opened 2021-08-25 02:00 UTC by zoq

As discussed here https://github.com/mlpack/ensmallen/pull/315 we like to bump the minimum Armadillo version to 9.800. I think once merged we should do another release `2.18.0`.

2021-08-25 06:36 UTC, conradsnicta requested changes

2021-08-25 06:36 UTC, conradsnicta commented on .travis.yml
> +      curl https://ftp.fau.de/macports/distfiles/armadillo/armadillo-9.800.1.tar.xz | tar -xvJ && cd armadillo*;
Suggest to use 9.800.6 instead, directly from Sourceforge:
https://sourceforge.net/projects/arma/files/armadillo-9.800.6.tar.xz
the .6 patch release is the last release in the 9.800.x series.

I'm not going to delete the above file (until at least when ensmallen updates its minimum armadillo version), so it's safe to use.  The previous situation which resulted in old armadillo releases being removed no longer applies.

2021-08-25 06:36 UTC, conradsnicta commented on README.md
> +* Ryan R. Curtin, Marcus Edel, Rahul Ganesh Prabhu, Suryoday Basak, Zhihao Lou, Conrad Sanderson.
Please keep the two blank spaces at the end of each line containing the author names and article name. Markdown interprets two spaces followed by a linebreak as a "forced linebreak".  In this case we need the forced linebreaks to ensure proper layout (to facilitate reading).

2021-08-28 02:07 UTC, rcurtin commented
When this is merged, we should also bump it in mlpack, otherwise we can get a situation where mlpack's Armadillo version requirement is less than ensmallen's, so a user could feasible download mlpack, download Armadillo 8.400.0, think "I'm good to go!", then suddenly find out that the newest ensmallen (via the autodownloader) actually needs an even newer version.

2021-08-28 16:39 UTC, shrit approved these changes

2021-08-28 16:40 UTC, shrit commented
It is strange the error says it is unable to find Armadillo on windows

2021-08-29 00:00 UTC, zoq commented
I'll fix the windows build.

2021-08-29 00:06 UTC, zoq commented
The auto-downloader downloads the ensmallen master branch? If that is the case, we should change that behavior, it should always download the latest stable version. Anyway, I'll open another PR on mlpack. With the release of another ensmallen, I also open a second PR to update ensmallen.org.

2021-08-30 01:58 UTC, merged

2021-08-30 02:01 UTC, rcurtin commented
> The auto-downloader downloads the ensmallen master branch? If that is the case, we should change that behavior, it should always download the latest stable version.

Right, it just downloads the latest stable version.  So, we should just merge mlpack/mlpack#3043 before releasing another version of ensmallen. :+1: